byteps/tensorflow/ops.py

@ymjiang Please run test and verify this works for both python2 and python3

tensorflow: fix python3 ctypes.c_char_p problem

---

byteps/tensorflow/__init__.py
byteps/tensorflow/ops.py

Addressing https://github.com/bytedance/byteps/issues/13
@ymjiang , we must verify the training result correctness before merging this.

tensorflow: better handling name_scope

---

byteps/tensorflow/ops.py

See https://github.com/bytedance/byteps/issues/13

tensorflow: quick fix for scope problem

---

byteps/mxnet/__init__.py
example/mxnet-gluon/run_mnist_gluon.sh
example/mxnet-gluon/train_mnist_byteps.py

Hi,
I followed the code of horovod, add example for mxnet gluon.
Two changes here:
1. DistributedTrainer for mxnet gluon API 
```python
trainer = bps.DistributedTrainer(params, "sgd", optimizer_params)
...
for i, batch in enumerate(train_data):
...
loss.backward()
trainer.step(args.batch_size)
```
2. An example of mxnet gluon training scripts.
```shell
cd byteps
bash example/mxnet-gluon/run_mnist_gluon.sh 
```
I test the script with ENVS:
- ubuntu 18.04
- mxnet 1.5.0
- cuda 10.0 with GTX1070*2
- python 3.5.2 (anaconda)
The expected output:
```
BytePS launching worker
INFO:root:Namespace(batch_size=64, dtype='float32', epochs=5, j=2, lr=0.01, momentum=0.9, no_cuda=False)
INFO:root:Namespace(batch_size=64, dtype='float32', epochs=5, j=2, lr=0.01, momentum=0.9, no_cuda=False)
... …
```

example: Add MXNet Gluon training example of MNIST.

---

example/mxnet-gluon/train_mnist_byteps.py

Following #54, the [mxnet-gluon example](https://github.com/bytedance/byteps/blob/master/example/mxnet-gluon/train_mnist_byteps.py) will crash (`server` crashes in RDMA layer) when `byteps` uses RDMA (`DMLC_ENABLE_RDMA=1`). 
The example initializes `byteps` (**with RDMA**), and then creates gluon data loader ([code](https://github.com/bytedance/byteps/blob/8dce68839cde5236a0bf908bc765d730df9c339d/example/mxnet-gluon/train_mnist_byteps.py#L100#L108)).
```python
bps.init()
context = mx.cpu(bps.local_rank()) if args.no_cuda else mx.gpu(bps.local_rank())
num_workers = bps.size()
train_data, val_data, train_size = get_mnist_iterator()
```
As explained by @ymjiang in #54, the default (multi-process) gluon data loader forks from the RDMA process which may lead to unexpected errors …

mxnet-gluon example (with RDMA): create gluon data loader before initializing byteps

---

docs/step-by-step-tutorial.md

Address the common performance issues, such as https://github.com/bytedance/byteps/issues/68 and https://github.com/bytedance/byteps/issues/78.

docs: pin down server omp thread number 

---

byteps/torch/__init__.py

Hi, 
I just found out that the BytePS distributed training in Pytorch will stuck at 
```c++
BytePSGlobal::GetPS()->Wait(BytePSGlobal::GetPS()->ZPush(pskv.keys, vals, pskv.lens, cmd));
```
The problem was that the initialized Tensor that sending to the PS in different machines have different keys, then it stuck.
It is because the passing order of the Tensor declaration is not sorted. In `byteps/torch/__init__.py`, even `self._parameter_names` is already sorted but `self._parameter_names.values()` will return an unsorted order to BytePS. 
Thanks,
Lam

Bug fixed: PyTorch distributed training stuck

---

byteps/torch/__init__.py

Asynchronous training implementation for PyTorch. Similar to https://github.com/bytedance/byteps/pull/114 for MXNet. 
Usage: `export BYTEPS_ENABLE_ASYNC=1`

torch: enable async training

---

README.md
byteps/tensorflow/__init__.py
byteps/tensorflow/ops.py
docs/env.md
example/tensorflow/run_tensorflow_byteps.sh
example/tensorflow/synthetic_benchmark.py
example/tensorflow/tensorflow_mnist.py

Asynchronous training implementation for TensorFlow. Similar to https://github.com/bytedance/byteps/pull/114 (MXNet) and https://github.com/bytedance/byteps/pull/121 (PyTorch). 
Usage: `export BYTEPS_ENABLE_ASYNC=1`

tf: enable async training

---

example/mxnet-gluon/train_mnist_byteps.py

remove `bps.broadcast_parameters(params, root_rank=0)` for gluon trainer

examples: remove broadcast in gluon example

---

launcher/launch.py

with `export BYTEPS_ENABLE_GDB=0 `, the python statement `if int(os.getenv("BYTEPS_ENABLE_GDB", 0))` will evaluate as True (`'0'`).

launcher: fix gdb init knob

---

byteps/common/global.cc
byteps/common/global.h

Improve the built in hash function, and add two advanced hash functions `DJB2` and `SDBM` ([reference](http://www.cse.yorku.ca/~oz/hash.html)). Use `BYTEPS_KEY_HASH_FN` to choose one of them.
Use `DJB2` as the default. For example, on Gluon-BERT training, the hash result is:
(`naive` and `built_in` perform bad in the same case)
```
2 servers
server 0, accumulated workload for this server is 671807488
server 1, accumulated workload for this server is 668825212
4 servers
server 0, accumulated workload for this server is 302258180
server 1, accumulated workload for this server is 342281848
server 2, accumulated workload for this server is 373814900
server 3, accumulated workload for this server is 326547460
8 servers
server 0, accumulated workload for this server is 146038784
server 1, …
```

common: add multiple key hash functions

---

byteps/mxnet/ops.cc
byteps/mxnet/tensor_util.cc

A few symbols are not exported in the latest nightly version of MXNet, which breaks byteps. Related thread: https://github.com/apache/incubator-mxnet/pull/15591 and https://github.com/bytedance/byteps/issues/173 
This PR replaces context creation and ndarray creation with c_apis to avoid the issue.

mxnet: Use C_API for creating NDArray and Context 

---

.gitignore
MANIFEST.in
byteps/common/global.h
byteps/common/shared_memory.cc
launcher/launch.py
setup.py

Also add a `bpslaunch` command, which can replace `launch.py`.

common: fix rdma fork problem

---

byteps/common/global.cc
byteps/common/global.h

Usage:
`export BYTEPS_ENABLE_MIXED_MODE=1` for scheduler and workers.

common: colocate and non-colocate mixed mode

---

byteps/mxnet/__init__.py
byteps/mxnet/ops.cc

BytePS assumes that the tensor it takes will not be freed during pushpull. This holds true in current situations where params or grads are always kept in _ParameterDict_. But when taking a temporary tensor as input, the tensor may be freed in the python thread but BytePS does not know that due to MXNet's asynchronous execution, which leads to a crash in BytePS. 
This problem has been fix in horovod. see 
https://github.com/horovod/horovod/pull/1639
https://github.com/horovod/horovod/pull/1718
By storing a shallow copy of the tensor in `PushPullParam`, its lifecycle will expand to pushpull operation ending.

mxnet: rm wait_to_read

---

MANIFEST.in
pre_setup.py
setup.py

add two optional environment variables:
BYTEPS_PRE_SETUP_SCRIPT
shell commands to run. e.g. BYTEPS_PRE_SETUP_SCRIPT="yum install -y gcc"
intalls gcc.
BYTEPS_EXTRA_MAKE_OPTION
additional options to pass to make when installing third party
dependencies.

build: update setup.py

---

byteps/torch/__init__.py
setup.py

After optimizer.skip_synchronization() is called, optimizer.step()
returns after triggering push-pull. Otherwise the local gradients from
the current pass will be lost.
Fix license classifier.
Add OS classifier.

torch: forbid using skip_synchronize in async training

---

setup.py

Address https://github.com/bytedance/byteps/issues/222 and https://github.com/apache/incubator-mxnet/issues/18014. In short, the problem is that BytePS will run into segfault if using `mxnet-cu100mkl`.
Tested it with mxnet-cu100mkl==1.5.0.

setup: fix mxnet-mkl segmentation fault

---

byteps/tensorflow/__init__.py
byteps/tensorflow/distribute/__init__.py
byteps/tensorflow/distribute/cross_device_ops.py
byteps/tensorflow/distribute/mirrored_strategy.py
docs/MirroredStrategy.md
example/tensorflow/tensorflow2_mnist_bps_MirroredStrategy.py

add byteps.tensorflow.MirroredStrategy. It runs in single-process
single-GPU mode, works as a repalcement for
tf.MultiWorkerMirroredStrategy.

add tf distributed strategy

---

byteps/server/server.cc

Attempt to fix https://github.com/bytedance/byteps/issues/279. Actually update_buf_ does not need to be freed (all its buffers are managed by ps-lite).

server: fix server improper free

---

launcher/launch.py

Do not launch server or scheduler when there's only one worker. To
launch server and scheduler anyway, do this:
export BYTEPS_FORCE_DISTRIBUTED=1

launcher: launching single-worker

---

byteps/common/global.h
byteps/common/operations.cc

Fix a bug that happens when the size of the tensor is larger than MAX_INT

common: Support tensors larger than 2GB

---

launcher/launch.py

When GDB is enabled, run servers under GDB as well.

test: run servers under gdb when gdb is enabled

---

MANIFEST.in
setup.py

ignore temporary build directories in packaging.

packaging: ignore temp build directories

---

example/tensorflow/synthetic_benchmark_tf2.py

There is a bug when I run the synthetic_benchmark_tf2.py.
The first parameter of [tf.losses.categorical_crossentropy](https://www.tensorflow.org/api_docs/python/tf/keras/losses/categorical_crossentropy) should be a tensor of one-hot true targets, but the parameter in this code is just integer. So, we should use [sparse_categorical_crossentropy](https://www.tensorflow.org/api_docs/python/tf/keras/losses/sparse_categorical_crossentropy).
I have fixed this bug.

example: Update synthetic_benchmark_tf2.py

---

byteps/tensorflow/__init__.py

In `tensorflow.push_pull` function, `op` is a `enum` type while `Average` is a str type, which means they can never equal. Now `tensorflow.push_pull` can only give SUM of tensors instead of AVERAGE. This pull request fix the bug.
See https://github.com/bytedance/byteps/issues/323

fix bug in tensorflow.push_pull

---

example/pytorch/train_mnist_byteps.py

fix the train_mnist_byteps.py example in torch

torch: fix the mnist example in torch

---

byteps/torch/ops.cc

use floor_divide_() to compute average in newer torch.

torch: use floor_divide_() for newer torch

---

setup.py

If an extension is explictly disabled by:
export BYTEPS_WITHOUT_MXNET=1
export BYTEPS_WITHOUT_PYTORCH=1
export BYTEPS_WITHOUT_TENSORFLOW=1
do not try to install it.

build: skip installing disabled extensions

---

byteps/torch/ops.cc

mark task done after averaging an int tensor. This fixes a bug
introduced in 46944e8.

torch: fix hang after int tensor push_pull

---

example/pytorch/benchmark_byteps.py

torch.autograd.profiler.profile() will not take 3 positional argumens (self, False, True) when enabled=False with the latest change to PyTorch source code.
This means that:
bpslaunch python benchmark_byteps.py --fp16-pushpull
fails with:
with torch.autograd.profiler.profile(False, True) as prof:                                                                               
TypeError: __init__() takes from 1 to 2 positional arguments but 3 were given
To fix this:
Use keyword arguments (enabled=enable_profiling, use_cuda=True)

torch.autograd.profiler.profile() keyword argument

---

.travis.yml
byteps/tensorflow/ops.py

register gradient operation for "BytepsPushPull" instead of
"BytePSPushPull". This matches the case in REGISTER_OP. Fixes the
following error:
LookupError: gradient registry has no entry for: BytepsPushPull

tf: fix case in register gradient

---

example/pytorch/mnist-distributed.py

fix the import statement in pytorch/mnist-distributed.py for python 3.8
fixes https://github.com/bytedance/byteps/issues/376

example: fix import for python3.8

---

byteps/tensorflow/ops.py

when run the test code, I meet the problem below, try to fix it..
```shell
File "/usr/local/lib/python3.6/dist-packages/byteps/tensorflow/__init__.py", line 66, in push_pull
op = handle_average_backwards_compatibility(op, average)
File "/usr/local/lib/python3.6/dist-packages/byteps/tensorflow/ops.py", line 83, in impl
warnings.warn('Parameter `average` has been replaced with `op` and will be removed',
NameError: name 'warnings' is not defined
```

fix missing import 'warnings'

---

byteps/server/server.cc
setup.py

- fix bool env parsing in server.cc
- disable avx512 when compiling. enabling avx512 may cause tensorflow
extension build failure. avx512 support in Eigen is likely not stable
yet.
Signed-off-by: yulu.jia <yulu.jia@bytedance.com>

fix bool env, disable avx512

---

docs/env.md
launcher/launch.py

assign physical cores to byteps workers, such that:
1) one worker's cores are on the same numa node with its GPU
2) one worker's cores don't overlap with another worker's cores
3) if hyperthreading is enabled, assign logical cores to the worker as well.
4) the number of physical cores assigned to each worker is calculated:
total number of physical cores / number of byteps workers
BYTEPS_VISIBLE_CPU_CORES can be used to override the auto core
assignment.

update core binding policy

---

MANIFEST.in
byteps/common/global.cc
byteps/common/shared_memory.cc
byteps/server/server.cc
byteps/server/server.h
setup.py

uplate ps-lite to the latest commit.

Update ps lite

---

launcher/launch.py

disable ucx signal handlers so that some faulty user code can still run
even if some child process of the program encounters a segfault.

ps-lite: disable ucx error handling by default
