- .travis.yml
- README.md
- setup.py
Build tests only. We might need to include more tests later.
> ci: initial commits

- byteps/torch/__init__.py
- byteps/torch/ops.py
- example/pytorch/train_mnist_byteps.py
Addressing https://github.com/bytedance/byteps/issues/35
> torch: expose push_pull api

- byteps/common/cpu_reducer.cc
- byteps/common/cpu_reducer.h
Addressing the performance issue mentioned in https://github.com/bytedance/byteps/issues/17
> common: make omp threads configurable

- byteps/mxnet/__init__.py
This is my implement to address https://github.com/bytedance/byteps/issues/44.
I have to say sorry first that there is a problem in `DistributedTrainer` of last PR.
Changes in this PR :
1. Fix `_allreduce_grads()` added in https://github.com/bytedance/byteps/pull/22 .
I made a mistake push/pull the gradients to name "parameter_".
```python
byteps_push_pull(param.list_grad()[0], is_average=False, 
name="parameter_"+str(i), priority=-i)
byteps_declare_tensor(param.list_grad()[0], "gradient_" + str(i))
byteps_push_pull(param.list_grad()[0], is_average=False,
name="gradient_" + str(i), priority=-i)
```
2. Attempt to address #44 
I removed the code, which try to process gluon deferred parameter but failed, from broadcast_parameters().
Overwrite the function _init_params, in super class …
> mxnet: code style improvement and gluon parameter broadcast enhancement

- byteps/common/operations.cc
- byteps/tensorflow/ops.py
For training very large models like BERT-large
> tensorflow: reduce memory footprint during broadcast

- byteps/common/cpu_reducer.cc
- byteps/common/cpu_reducer.h
Notes:
1. It can compile, but the correctness is unknown yet;
2. Openmp pragma is not added yet.
> Improve fp16 cpu-sum performance

- byteps/common/communicator.cc
To handle the "Interrupted system call" error when a socket is receiving messages. This has been tested with mxnet.
> common: add socket-recv EINTR handle

- example/mxnet/common/data_byteps.py
See https://github.com/bytedance/byteps/issues/34#issuecomment-509323272
> example: fix MXNet example cpu device ID

- byteps/common/scheduled_queue.cc
- byteps/misc/imagenet18/__init__.py
- byteps/torch/__init__.py
- byteps/torch/ops.cc
- byteps/torch/ops.h
- byteps/torch/ops.py
For training ImageNet in 18min
> torch: improve pytorch compatibility and add imagenet18 support

- bytescheduler/bytescheduler/tensorflow/tf.patch
> Update patch to TensorFlow

- bytescheduler/README.md
- bytescheduler/docs/scheduling.md
Clarify the code usage and limitations.
> improve docs

- byteps/mxnet/__init__.py
The associated modification on server is at https://github.com/bytedance/incubator-mxnet/pull/2
Usage: `export BYTEPS_ENABLE_ASYNC=1`
Async training for TensorFlow and PyTorch will be added soon.
> mxnet: enable async training

- byteps/mxnet/ops.cc
to avoid ABI compatibility issues. With this fix, byteps does not have to be compiled with GCC 4.8.
> mxnet: fix ABI compatibility issues

- launcher/launch.py
Address https://github.com/bytedance/byteps/issues/127
> launcher: check necessary env var

- byteps/common/communicator.cc
- byteps/common/communicator.h
- byteps/common/core_loops.cc
- byteps/common/global.cc
- byteps/common/global.h
- byteps/common/operations.cc
- byteps/common/shared_memory.h
Address issues such as https://github.com/bytedance/byteps/issues/135 and https://github.com/bytedance/byteps/issues/85
> common: fix crashing problem when shutdown

- byteps/bytescheduler/torch/optimizer.py
> add id() op for bytescheduler.torch.optimizer.py

- byteps/mxnet/__init__.py
- byteps/mxnet/ops.cc
- byteps/mxnet/ops.h
- byteps/mxnet/ops.py
- tests/run_byteps_test.sh
- tests/test_mxnet.py
Fix https://github.com/bytedance/byteps/issues/175
> mxnet: trainer initialization 

- tests/test_mxnet.py
> mxnet: fix test 

- example/mxnet/train_gluon_mnist_byteps.py
> mxnet: fix example

- byteps/common/__init__.py
- byteps/common/global.cc
- byteps/common/global.h
- byteps/common/operations.cc
- byteps/common/operations.h
- byteps/mxnet/__init__.py
- byteps/mxnet/ops.py
- byteps/tensorflow/__init__.py
- byteps/tensorflow/ops.py
- byteps/torch/__init__.py
- byteps/torch/ops.py
Expose 2 APIs, i.e., suspend and resume, for elastic training with dynamic number of workers and parameter servers.
> Enable Elastic Training on BytePS

- .github/ISSUE_TEMPLATE/bug_report.md
- README.md
- byteps/common/communicator.cc
- byteps/common/core_loops.cc
- byteps/common/cpu_reducer.cc
- byteps/common/global.cc
- byteps/common/global.h
- byteps/common/scheduled_queue.cc
- byteps/misc/imagenet18/__init__.py
- byteps/mxnet/__init__.py
- byteps/server/queue.h
- byteps/server/server.cc
- byteps/server/server.h
- byteps/torch/__init__.py
- docker/Dockerfile
- docker/README.md
- docs/architecture.md
- docs/best-practice.md
- docs/cross-barrier.md
- docs/env.md
- docs/performance.md
- docs/rationale.md
- docs/step-by-step-tutorial.md
- docs/timeline.md
- docs/troubleshooting.md
- example/mxnet/common/fit.py
- example/mxnet/symbols/mobilenetv2.py
- example/pytorch/benchmark_cross_barrier_byteps.py
- launcher/README.md
Remove trailing whitespace from all files.
> misc: strip trailing whitespace

- byteps/torch/__init__.py
To better support PyTorch Apex.
> torch: add skip_synchronize api

- byteps/torch/__init__.py
import contextmanager in torch/__init__.py
> torch: import contextmanager

- byteps/common/operations.cc
Trying to address https://github.com/bytedance/byteps/issues/247
> common: fix the problem of different CPU tensor using the same name

- byteps/__version__.py
- setup.py
- bump version number to 0.2.3
- fix license name in setup.py
> build: bump version number to 0.2.3

- byteps/_keras/__init__.py
- byteps/_keras/callbacks.py
- byteps/common/core_loops.cc
- byteps/common/global.cc
- byteps/common/operations.cc
- byteps/keras/__init__.py
- byteps/keras/callbacks.py
- byteps/tensorflow/__init__.py
- byteps/tensorflow/keras/__init__.py
- byteps/tensorflow/keras/callbacks.py
- byteps/tensorflow/ops.cc
- byteps/tensorflow/ops.py
- example/keras/keras_mnist.py
- example/keras/keras_synthetic_benchmark_tf2.py
- example/tensorflow/tensorflow2_keras_mnist.py
- example/tensorflow/tensorflow_keras_mnist.py
fix compatibility issue with tf2 keras.
> [WIP] tensorflow: fix compatibility issue with tf2 keras

- docs/run-on-k8s.md
Since the impressive performance of BytePS is getting recognized, more and more people are trying to launch BytePS job on K8s. Here is a little guide showing you how to do it with latest MXNet-Operator.
> Add tutorial: How to Run BytePS on K8s

- byteps/torch/ops.cc
- byteps/torch/ops.h
Add alias function so that push_pull works with torch.ByteTensor
> torch: add ByteTensor support

- byteps/__version__.py
- launcher/launch.py
- setup.py
> bump up version to 0.2.5-1

- byteps/__version__.py
- setup.py
> bump version number to 0.2.5

- byteps/common/core_loops.cc
> fix type not found error

- MANIFEST.in
- setup.py
update ps-lite submodule to utilize the new ucx van.
> update ps lite

- pre_setup.py
- setup.py
do not build ucx by default. fixes https://github.com/bytedance/byteps/issues/329
> build: fix ucx build

- byteps/tensorflow/__init__.py
- setup.py
Skip broadcasting variables if there's only one worker
> tf: skip bcast if there's only one worker

- docs/env.md
- launcher/launch.py
change semicolon-separated to colon-separated
> update doc for core affinity envs

- setup.py
automatically download zeromq and ucx tarballs when running:
python3 setup.py sdist
Signed-off-by: yulu.jia <yulu.jia@bytedance.com>
> packaging: download tarballs when running sdist
